spring.application.name=clinicamedica

spring.datasource.url=jdbc:mysql://mysql:3306/clinicamedica
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true